const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./server.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "API GoStyle",
        description: "Documentation automatically generated by the <b>swagger.autogen</b> module."
    },
    host: "localhost:8080",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],

    securityDefinitions: {
        Bearer: {
            type: "apiKey",
            name: "Authorization",
            in: "header",
            description: "Enter your bearer token in the format **Bearer &lt;token>**"
        }
    },
}



swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./server.js')

})

